## Dovecot OSS minimal — auth Postgres + Maildir, IMAP plaintext interne.
protocols = imap lmtp

# Auth via Postgres
disable_plaintext_auth = no
auth_mechanisms = plain login
passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql-tokens.conf.ext
}
userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

# Stockage Maildir par user
mail_location = maildir:/var/vmail/%d/%n/Maildir
mail_uid = vmail
mail_gid = vmail
first_valid_uid = 5000
first_valid_gid = 5000

# TLS pour IMAPS (port 993). Cert auto-signé généré par entrypoint si absent.
ssl = yes
ssl_cert = </etc/dovecot/tls/cert.pem
ssl_key  = </etc/dovecot/tls/key.pem
ssl_min_protocol = TLSv1.2

# Services
service auth {
  unix_listener auth-userdb {
    user = vmail
  }
  # Socket UNIX pour Postfix SASL (montée dans le spool postfix)
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  # Listener TCP pour SASL distant (useful pour OSS multi-host)
  inet_listener {
    port = 12345
  }
}
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl  = yes
  }
}
service lmtp {
  inet_listener lmtp {
    port = 24
  }
  # Socket UNIX pour Postfix virtual_transport = lmtp:unix:private/dovecot-lmtp
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

# Logs vers stderr
log_path = /dev/stderr
info_log_path = /dev/stderr
debug_log_path = /dev/stderr

# Namespace INBOX standard
namespace inbox {
  inbox = yes
  separator = /
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
}

# Master user pour le webmail (passwd-file géré par entrypoint)
auth_master_user_separator = *
passdb {
  driver = passwd-file
  master = yes
  args = /etc/dovecot/master-users
  result_success = continue-ok
}
