enabled = true;
selector = "mail";
path = "/var/lib/rspamd/dkim/$domain.$selector.key";
allow_username_mismatch = true;
use_domain = "envelope";
sign_local = true;
sign_networks = ["5.196.149.65/32", "141.94.30.110/32"];
