use = ["x-spamd-result", "authentication-results", "x-spam-status", "x-spam-level"];
authenticated_headers = ["authentication-results"];
extended_spam_headers = true;
skip_local = true;
skip_authenticated = true;
remove_headers = {
  "Authentication-Results" = 0;
  "X-Spamd-Result" = 0;
  "X-Spam-Status" = 0;
  "X-Spam-Level" = 0;
};
